
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1095000528702-p51h791nmkpvogrnb3fmcd31dv1pbkoh.apps.googleusercontent.com
            client-secret: _oLxYqLqjPuhsW9ilxIZC_Sg

#logging:
#  level:
#    org.springframework.security: DEBUG
